data:
  train_files: /tmp/shared-storage/lishichao/EasyR1/data/omnimedvqa/ISIC/few_shot/16-shot/train.jsonl
  val_files: /tmp/shared-storage/lishichao/EasyR1/data/omnimedvqa/ISIC/val.jsonl
  prompt_key: prompt
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 2048
  max_response_length: 2048
  rollout_batch_size: 32
  mini_rollout_batch_size: null
  val_batch_size: 2
  format_prompt: ./examples/Omini/ISIC/format_prompt/isic.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: true
  oracle_redis_url: redis://localhost:6381/0
  oracle_queue_key: oracle_queue

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    loss_type: gspo_token
    loss_avg_mode: seq
    clip_ratio_low: 3e-4
    clip_ratio_high: 4e-4
    global_batch_size: 32
    micro_batch_size_per_device_for_update: 2
    micro_batch_size_per_device_for_experience: 4
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 8
    # max_model_len: 8192
    temperature: 0.7
    top_p: 0.9
    limit_images: 0
    gpu_memory_utilization: 0.8
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_function: ./oracle_grpo/reward/logic_reward.py:compute_score

trainer:
  total_epochs: 200
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_isic_oracle_grpo
  logger: ["file", "swanlab"]
  nnodes: 1
  n_gpus_per_node: 4
  max_try_make_batch: 20
  val_freq: -1
  val_before_train: false
  val_only: false
  val_generations_to_log: 6
  save_freq: 5
  save_limit: 3
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
